`````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
`````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
`````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
`````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````



`````````````````````````````````````````````````````````````````````````````````````````````````````````````````` 성공환경 s
me : python 을 통한 내부망에 연결된 PC 간에 10GB 미만파일 전송에 성공했다.
`````````````````````````````````````````````````````````````````````````````````````````````````````````````````` 성공환경 s
